version: "3.8"
services:
    web:
      image: "${DOCKER_PHP_IMAGE}"
      ports:
      - "8001-8002:80"
      deploy:
          replicas: 2
      depends_on:
      - mysql
    mysql:
      image: manoranjan555/deploy:mysql
      volumes:
      - db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydatabase
volumes:
   db_data: {}
